from src.schemas import DescriptionOutput
from langchain.agents import create_agent

from src.llm.llm import get_llm
from src.schemas import VerificationResult
from src.agents.description import describe_component

SYSTEM_PROMPT = """You are the Verification Agent in the Spec2RTL-Agent system.

Compare the supplied hardware specification evidence with the supplied
component description using static textual review only.

The specification evidence comes from the original hardware specification.
The component description was generated by another agent.

Your task is to determine whether the component description is supported
by the supplied specification evidence.

Do not invent requirements that are not stated in the specification.
Do not assume behavior that is not explicitly supported by the specification.
Do not modify or rewrite the component description.

Check for:
- Whether the described component is supported by the specification
- Whether its purpose and functionality match the specification
- Whether required inputs and outputs are correctly described
- Whether signal names, widths, and interfaces mentioned in the description
  match the specification
- Whether constraints or behavioral requirements are correctly represented
- Missing required behavior
- Contradictions between the description and specification
- Claims in the description that cannot be established from the specification

For VerificationResult:
- Set valid to true only when the component description is consistent with
  the supplied specification evidence and no clear mismatch is found.
- Set valid to false when a clear contradiction, incorrect claim, or missing
  required behavior is found.
- Put contradictions, missing information, and unsupported claims in issues.
- Do not present uncertain conclusions as facts.
- Explain the evidence used for the decision in reasoning.
- If the supplied specification evidence is insufficient to verify a claim,
  explicitly state that it cannot be established from the provided evidence.

The final response must conform strictly to the VerificationResult schema.
"""

def create_verification_agent():
  return create_agent(
    model= get_llm(),
    tools=[],
    response_format = VerificationResult,
    system_prompt = SYSTEM_PROMPT


  )


def verify_description(source_chunks:list,description:DescriptionOutput)-> VerificationResult:
  agent = create_verification_agent()

  specifications = "\n\n".join(doc.page_content for doc in source_chunks)

  

  result = agent.invoke(
    {
      "messages":[
        {
          "role":"user",
          "content":f"""
          Original Specification : 
          {specifications}

          Description to Verify:
          {description.model_dump_json(indent=2)}
          Verify the description against the original specification."""

          
        }
      ]
    }
  )
  return result['structured_response']

